- census_example.ipynb
- forest_example.ipynb
- pytorch_tabnet/tab_model.py
We were converting targets to `long` even when `output_dim=1`.
> fix: float type when output_dim=1

- .gitignore
- census_example.ipynb
- forest_example.ipynb
- pytorch_tabnet/tab_model.py
- pytorch_tabnet/utils.py
Adds softmax and create few functions, everything by chunks
> fix: add softmax to predict_proba

- pyproject.toml
> chore: update version to 0.1.1

- Dockerfile
> chore: adding OpenBlas to docker image

- CHANGELOG.md
- pyproject.toml
> chore: release v0.1.2

- pytorch_tabnet/tab_network.py
> fix: remove torch warnings (index should be bool

- pytorch_tabnet/tab_model.py
This PR simply adds a missing else statement for weighted classification problems.
Minor change.
> fix: functional balanced version

- README.md
- pytorch_tabnet/tab_model.py
- pytorch_tabnet/tab_network.py
This PR adds representation string to get some information about a model.
Nope
Some default values have been added, README has been updated accordingly.
> chore: add representation strings

- README.md
- pytorch_tabnet/tab_model.py
> chore(doc): update README

- pytorch_tabnet/tab_model.py
- regression_example.ipynb
Quick bugfixes for gpu and regression integration as well as fixing some types on the regression notebook.
> fix: regression gpu integration an typos

- census_example.ipynb
- pytorch_tabnet/tab_model.py
- pytorch_tabnet/tab_network.py
- pytorch_tabnet/utils.py
This fixes a bug about local explainability. Only the last batch was returned instead of all explanations.
This PR closes #45 as it's finally more than just going to numpy.
It also fixes the dimensionality and close #49 
> fix: local explain all batches

- pytorch_tabnet/tab_model.py
This removes some legacy code in TabNetRegressor that creates a bug when using schedulers
> fix(regression): fix scheduler

- pytorch_tabnet/tab_network.py
This change the way the embedding layers are stacked together.
The general idea is to keep the same order as the initial dataset.
There used to be a mismatch between the importance order and the initial feature order.
No breaking change, everything's hidden to users.
> fix: importance indexing fixed

- .gitignore
- pytorch_tabnet/tab_model.py
Print evaluation metrics instead of plotting.
> feat: plot --> text metrics

- census_example.ipynb
- forest_example.ipynb
- pytorch_tabnet/tab_model.py
- regression_example.ipynb
Easy fix for timer and warnings due to pytorch 1.3 bug
> fix: resolve timer issue and warnings

- census_example.ipynb
- forest_example.ipynb
- pytorch_tabnet/tab_model.py
This PR solves problem encountered in #70, there was a prediction mapping missing.
This solves the problem.
No breaking change
> fix: multiclass prediction mapper

- README.md
> docs: duplicate documentation for `scheduler_params`

- census_example.ipynb
- pytorch_tabnet/tab_model.py
- pytorch_tabnet/tab_network.py
Small changes in order to solve #78 
> fix: allow smaller different nshared and nindependent

- census_example.ipynb
> chore: update notebook

- release-script/do-release.sh
- release-script/prepare-release.sh
> chore: wrong image name in scripts

- census_example.ipynb
- forest_example.ipynb
- pytorch_tabnet/tab_model.py
- regression_example.ipynb
This is a bug fix, embeddings with regression was not working
No breaking changes, everything should just be back to normal
> fix : regression embeddings sizes

- pytorch_tabnet/tab_network.py
This clarifies and improves the embeddings via a clearer and smarter embeddings module.
Nothing new under the sun, no one should notice that when using tabnet.
nothing
closes #99
> chore: improve clarity and efficiency of embeddings

- README.md
- census_example.ipynb
- pytorch_tabnet/tab_model.py
- pytorch_tabnet/utils.py
- regression_example.ipynb
Adds num_workers as fit parameters and drop_last also
No breaking change just a new parameter
README needs to be updated
closes #98
> feat: add num_workers to fit parameters

- pytorch_tabnet/tab_network.py
Small speed improvement and simplification on ghost batch normalization
No.
https://github.com/dreamquark-ai/tabnet/issues/104
> feat: speed boost and code simplification for GBN

- forest_example.ipynb
Simply updates notebook for forest cover type
> fix: update forest_example notebook

- pytorch_tabnet/tab_network.py
> fix: allow zero layer

- Makefile
This adds the share memory configuration in the docker file.
It does not impact the package itself
> chore: update makefile for num workers

- pytorch_tabnet/tab_network.py
The fixed bug is described into this issue https://github.com/dreamquark-ai/tabnet/issues/119
Small fix into the network
No
Nothing
closes #119
> fix: sort by cat_idx into embedding generator

- pytorch_tabnet/tab_model.py
- pytorch_tabnet/tab_network.py
> feat: remove mask computations from forward

- .circleci/config.yml
- .gitignore
- Dockerfile
- Dockerfile_gpu
- Makefile
- census_example.ipynb
- forest_example.ipynb
- multi_regression_example.ipynb
- regression_example.ipynb
> chore: add notebook tests

- census_example.ipynb
- pytorch_tabnet/tab_model.py
- pytorch_tabnet/utils.py
This solves #132. 
Idea is to allow to give a list of weights per training sample to use during training.
No breaking changes.
still need to add more information in the README about this.
closes #132 
> feat: allow weights sample for regression

- README.md
- census_example.ipynb
- pytorch_tabnet/tab_model.py
- pytorch_tabnet/tab_network.py
After reading this https://towardsdatascience.com/the-unreasonable-ineffectiveness-of-deep-learning-on-tabular-data-fd784ea29c33
I thought it would be pretty easy to add a parameter to switch from sparsemax to entmax.
This allow to change the "mask_type" quite easily.
No breaking change jsut new features
I updtaed the README and added the parameter in census notebook
Put `closes #XXXX` in your comment to auto-close …
> feat: add entmax as parameter

- census_example.ipynb
- forest_example.ipynb
- pytorch_tabnet/tab_model.py
Save/load state dict with examples on notebooks.
No.
https://github.com/dreamquark-ai/tabnet/issues/138
**Closes** #136 #138
> feat: save and load tabnet models

- pytorch_tabnet/tab_model.py
Proposed fix for #163 - failure of `load_model()` in Python <3.7 environments.
This is a pretty quick & dirty approach aiming to minimise footprint of the code change for compatibility, but there could be other alternatives:
- Could try to detect the situation (e.g. via Python version detection or determining whether the returned `f` object is seekable) rather than handling as an error catch, if that's preferred? I was just trying to minimise the situations in which the file would be buffered into memory to only those where it was strictly necessary.
- Could try [this approach](https://stackoverflow.com/a/54199495/13352657) of hacking around with `f` to make it **look** seekable and hoping that's enough - …
> fix: load_model fallback to BytesIO for Py3.6

- forest_example.ipynb
Simple logic inversion on the type.
Bugfix
No
Nothing
> fix: 1000 lines only when env=CI

- README.md
- census_example.ipynb
- forest_example.ipynb
- multi_regression_example.ipynb
- multi_task_example.ipynb
- pytorch_tabnet/abstract_model.py
- pytorch_tabnet/callbacks.py
- pytorch_tabnet/metrics.py
- pytorch_tabnet/multiclass_utils.py
- pytorch_tabnet/multitask.py
- pytorch_tabnet/tab_model.py
- pytorch_tabnet/utils.py
- regression_example.ipynb
> feat: refacto and adding callbacks

- .circleci/config.yml
- Makefile
- README.md
- census_example.ipynb
- customizing_example.ipynb
- pytorch_tabnet/abstract_model.py
- pytorch_tabnet/callbacks.py
- pytorch_tabnet/metrics.py
This enables easy scheduling and adds some documentation
No breaking changes
> feat: add easy schedulers

- pytorch_tabnet/abstract_model.py
- pytorch_tabnet/utils.py
This is the same PR as #196 
Checks for nans and infinite values to through clear error
nope
nothing
closes #192
> feat: add check nan and inf

- pytorch_tabnet/abstract_model.py
- pytorch_tabnet/multitask.py
- pytorch_tabnet/tab_model.py
- pytorch_tabnet/utils.py
Minor changes which should speed up the trianing process related to  #183 
- get rig of optimizer.zero_grad()
- default pin_memory=True
nope results and usage are exactly the same
nothing
> feat: speedups

- pytorch_tabnet/abstract_model.py
Bugfix for loading models on CPU when their origin is a GPU environment. 
No.
Nothing.
Closes https://github.com/dreamquark-ai/tabnet/issues/197
> fix: add map_location to torch load

- pytorch_tabnet/multitask.py
This puts back the check for eval sets labels, currently we have an unreadable error
No just a bugfix
nothing
> fix: add check for evalset dim

- pytorch_tabnet/abstract_model.py
**What kind of change does this PR introduce?** Bug fix
**Does this PR introduce a breaking change?** No
**What needs to be documented once your changes are merged?** No change
**Closing issues** #204
*Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).*
I would argue the issue isn't really closed until released maybe? Last time there was a few months' gap from merge to release 😞
Could also consider a bit more refactoring of this, to try and minimise the possibility of similar issue in future? The try/except block is not *quite* DRY - but I thought …
> fix: torch.load map_location in Py36 fallback

- pytorch_tabnet/abstract_model.py
- pytorch_tabnet/utils.py
bugif for #206 
no
nothing
Close #206 
> fix: specify device

- pytorch_tabnet/abstract_model.py
- pytorch_tabnet/metrics.py
- pytorch_tabnet/multiclass_utils.py
- pytorch_tabnet/multitask.py
- pytorch_tabnet/sparsemax.py
- pytorch_tabnet/tab_model.py
- pytorch_tabnet/tab_network.py
- pytorch_tabnet/utils.py
Issue #203
Mostly docstring edts.
In a few places I've added info to docstrings, and those should probably get some extra checking to make sure they're correct.
In one place I've changed a parameter name (see next question).
This currently changes one function parameter name. This is probably the most controversial change here. I'm happy to change it back if the old name is preferred.
In `abstract_model.py`, in the method `TabModel.save_model()`, I've changed `path` to `filepath`. I made this change because the following method, `TabModel.load_model()` uses `filepath`, and there are common submodules in the …
> Docstring edits

- pytorch_tabnet/abstract_model.py
This is related to this discussion : #206
When device is cpu we should deactivate pin_memory, that's what this PR does.
No
Nothing
> fix: deactivate pin memory when device is cpu

- census_example.ipynb
- pytorch_tabnet/abstract_model.py
- pytorch_tabnet/utils.py
This is related to #214.
It will make smaller checks and allow strings as targets.
I tested it, seems like all error messages are ok.
Nope
nothing
closes #214
> fix: checknan allow string as targets

- pytorch_tabnet/tab_model.py
- pytorch_tabnet/utils.py
Simply add somes checks for better error message when dimensions are not right.
No
Nothg
None
> fix : regression dimension error message

- README.md
- multi_regression_example.ipynb
- pytorch_tabnet/metrics.py
- pytorch_tabnet/tab_network.py
- regression_example.ipynb
Adds a few metrics, update README and fix a minor f-string bug.
Nope
Already done in the README
Closes #228
> feat: add new default metrics

- pytorch_tabnet/multiclass_utils.py
The original error message from `TabNetClassifier` in response to multilabel classification is a little unclear (see #169). I just added a more helpful error message to reduce the potential confusion.
No
Nothing
> Add descriptive msg for TabNetClassifier multilabel classification

- README.md
- pytorch_tabnet/callbacks.py
- pytorch_tabnet/metrics.py
- pytorch_tabnet/multiclass_utils.py
- pytorch_tabnet/pretraining.py
- pytorch_tabnet/pretraining_utils.py
- pytorch_tabnet/sparsemax.py
- pytorch_tabnet/tab_model.py
- pytorch_tabnet/tab_network.py
- pytorch_tabnet/utils.py
fix typos in docstring.
closes #254
> chore: docstring typos

- .circleci/config.yml
- Makefile
- pytorch_tabnet/pretraining.py
Add preds_mapper to pretraining and include the pretraining notebook to the circleci config so that it is tested on every pull request.
Bugfix
No
Nothing
closes #264
> fix: add preds_mapper to pretraining

- README.md
> fixes minor README typos and improves readability and consistency

- README.md
Add commit conventions  to our README file.
No
Nothing
None
> docs: add conventional commits to readme

- Dockerfile_gpu
Changes the docker file gpu to avoid gpg key error
closes  #328 
> WIP fix: update gpg key in docker file gpu

- README.md
- census_example.ipynb
- pytorch_tabnet/abstract_model.py
- pytorch_tabnet/pretraining.py
- pytorch_tabnet/utils.py
This introduces a `warm_start` for the fit method to match scikit-learn's api: as discussed here #271.
TODO: test that training is reproducible in a for loop without redifining the model class
-> Done I forgot to update the pretrainer now it's done, also changed the way we set the seed to get reproducible results at consecutive run
This adds a new feature and swtich the default behavior, so this IS considered a breaking change even though it does change anything for most pipelines.
I changed the README to match new behaviour.
closes #271
> feat: add warm_start matching scikit-learn

- pytorch_tabnet/tab_network.py
This is a minor refacto proposed in #447 
It does not change anything, just code cleaning
It does not close the issue since a real change could be implemented to get closer to original paper in pretraining
> WIP chore: minor refacto to simplify code

- pytorch_tabnet/pretraining.py
This fixes the bug #478, it adds back the two missing parameters
No breaking change.
No need for documentation as it's just a bug fix
closes #478
> fix-478: add n_shared_decoder and n_indep_decoder
